apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prueba
  template:
    metadata:
      labels:
        app: prueba
    spec:
      containers:
        - name: prueba
          image: nginx
          ports:
            - containerPort: 80
